name = 'Mini bau'
version = '0.0.1'
license = 'MIT'
licenselink = 'https://github.com/owner/repo/LICENSE'
description = 'Mini Bau is a Hugo theme for reapair and construction company site'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/owner/repo'

# If you have a running demo of the theme
demosite = 'https://owner.github.io/repo'

# Taxonomy terms
tags = ['blog', 'company']
features = ['some', 'awesome', 'features']

# If the theme has a single author
[author]
  name = 'Kolya_YA'
  homepage = 'plus360.eu'
